### ISSUE TITLE
Problem with AUS and USA data

### ISSUE THREAD

**Issue by shrutibhutaiya** [RutvijBhutaiya/COVID-19-Twitter-Analysis#1]
I feel there is some issue over here, Can you recheck and confirm.
Total_retweet_AUS | 27730
  | Total_Fav_Retweet_AUS | 3315
  | Total_retweet_USA | 27730
  | Total_Fav_Retweet_USA | 3315

**Comment by RutvijBhutaiya** [comment]
Yes, I changed the codes, by mistake I took the same account fro Australia as US. In the main code. I changed.
